# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
      npm install
  displayName: 'Instalando dependências'

- script: |
      npx cypress verify
  displayName: 'Verificando instalação do Cypress'

- script: |
      npx cypress run
  displayName: 'Executando testes'

- task: PublishTestResults@2
  displayName: 'Publicando Resultados dos Testes'
  inputs:
    testResultsFiles: '**/test-*.xml'
  condition: succeededOrFailed()
  continueOnError: true

- task: CopyFiles@2
  displayName: "Copiando artefatos do relatório para área de staging"
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/cypress/reports/html'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/reports'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: "Publicando artefatos"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    StoreAsTar: true
  condition: succeededOrFailed()

